# render.yaml
services:
  - type: web
    name: projecthub
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://projecthub_db_user:0kgThPalK6sitRb0JFyDaRtoM6zBEzao@dpg-d5ft3df5r7bs73ddbr60-a.frankfurt-postgres.render.com/projecthub_db"
      - key: SECRET_KEY
        value: "django-insecure-b*c15f(ojd-q@0b%za&+8u=vj5+x)6y=9bv@7%@55@klclm+n^"
      - key: PAYSTACK_SECRET_KEY
        value: "sk_test_e66649d8ec088de0c3d8a13a4eaa4da358ff5a33"
      - key: PAYSTACK_PUBLIC_KEY
        value: "pk_test_9be5827fe2a4ffcd8eeaf923b83dc6e5563acf42"
      - key: DEBUG
        value: "True"  # TEMPORARY - CHANGE TO False LATER
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DJANGO_SETTINGS_MODULE
        value: "backend.settings"