services:
  - type: web
    name: projecthub
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: postgresql://projecthub_db_user:0kgThPalK6sitRb0JFyDaRtoM6zBEzao@dpg-d5ft3df5r7bs73ddbr60-a.frankfurt-postgres.render.com/projecthub_db
        fromDatabase:
          name: projecthub-db
          property: connectionString
      - key: django-insecure-b*c15f(ojd-q@0b%za&+8u=vj5+x)6y=9bv@7%@55@klclm+n^

        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"
      - key: sk_test_e66649d8ec088de0c3d8a13a4eaa4da358ff5a33
        sync: false
      - key: pk_test_9be5827fe2a4ffcd8eeaf923b83dc6e5563acf42
        sync: false

databases:
  - name: projecthub-db
    databaseName: projecthub
    user: projecthub
    plan: free
